function Band = Filter_Band(Fstop1, Fpass1, Fpass2, Fstop2, Fs)
%FILTER_BAND Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 26-May-2020 17:54:16

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
% Fs = 44100;  % Sampling Frequency

% Fstop1 = 15;      % First Stopband Frequency
% Fpass1 = 20;      % First Passband Frequency
% Fpass2 = 20000;   % Second Passband Frequency
% Fstop2 = 20100;   % Second Stopband Frequency
Astop1 = 80;      % First Stopband Attenuation (dB)
Apass  = 0.1;     % Passband Ripple (dB)
Astop2 = 80;      % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
Band = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
